    <section id="Contacts List">
        <div class="add">
                <h1>Contacts List</h1>
        </div>
            <div>
                <table id="contacts">
                    <tr>
                        <th>ID</th>
                        <th>Firstname</th>
                        <th>Lastname</th>
                        <th>Email</th>
                        <th>Adress</th>
                        <th>Phone</th>
                        <th>Groupe</th>
                        <th>Actions</th>
                    </tr>
                    <tr>
                        <td>58011</td>
                        <td>Abby</td>
                        <td>Adams</td>
                        <th>Abby@anywhere.com</th>
                        <th>Adress1</th>
                        <th>Phone1</th>
                        <th>Family</th>
                        <th>Edit</th>
                    </tr>
                    <tr>
                        <td>58012</td>
                        <td>Barbara</td>
                        <td>Bardely</td>
                        <th>Barbara@anywhere.com</th>
                        <th>Adress2</th>
                        <th>Phone2</th>
                        <th>Family</th>
                        <th>Edit</th>
                    </tr>
                    <tr>
                        <td>58013</td>
                        <td>Casier</td>
                        <td>Cohen</td>
                        <th>Casier@anywhere.com</th>
                        <th>Adress3</th>
                        <th>Phone3</th>
                        <th>Friend</th>
                        <th>Edit</th>
                    </tr>
                    <tr>
                        <td>58014</td>
                        <td>Dana</td>
                        <td>Donnely</td>
                        <th>Dana@anywhere.com</th>
                        <th>Adress4</th>
                        <th>Phone4</th>
                        <th>Business</th>
                        <th>Edit</th>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </table>
            </div>
            <button class="button"><span>Logout </span></button>